### PR TITLE
[active-standby][bsl] fix no mux probe issue

### PR DESCRIPTION
**Pull request by zjswhhh**
### Description of PR

Summary:
Fixes # (issue)

Noticed an issue in BSL scenario that, both ToRs were be in `standby` state after mux service restart or reboot. The issue was due to no mux probe was triggered by linkmgrd. 

Root cause was link manager state machine corner case: 

* State machine activated as standby healthy after reboot or service restart
```
Apr 21 21:24:11.563419 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:478 activateStateMachine: Ethernet124: (P: Unknown, M: Standby, L: Up) -> (P: Standby, M: Standby, L: Up)
Apr 21 21:24:11.580274 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:291 setLabel: Ethernet124: Linkmgrd state is: Standby Healthy
```
* There is no heartbeat in L2 mode
```
Apr 21 21:24:11.889344 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:501 handleStateChange: Ethernet124: Received link prober event, new state: Unknown
Apr 21 21:24:11.889344 - WARNING mux#linkmgrd: DbInterface.cpp:175 postLinkProberMetricsEvent: Ethernet124: posting link prober event link_prober_unknown_start
```
* Switchover was skipped https://github.com/sonic-net/sonic-linkmgrd/blob/01792078de69b3205b870074dac3a9804f3e900e/src/link_manager/LinkManagerStateMachine.cpp#L1229-L1231
```
Apr 21 21:24:11.889344 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:525 handleStateChange: Ethernet124: (P: Standby, M: Standby, L: Up) -> (P: Wait, M: Standby, L: Up)
Apr 21 21:24:11.889344 - WARNING mux#linkmgrd: DbInterface.cpp:392 handlePostLinkProberMetrics: Ethernet124: posting link prober event link_prober_unknown_start
```
* No further toggle or mux probe is triggered. State machine is stuck. 
 
sign-off: Jing Zhang zhangjing@microsoft.com
### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Doc/Design
- [ ] Unit test

#### What is the motivation for this PR?
To unblock vendor side BSL tests. (A workaround to disable default route feature has been shared, this PR is a long-term fix.)

#### How did you do it?
Do mux probe when skipping toggle. 

#### How did you verify/test it?
* Followed the step to repro, with this change, issue can't be reproduced. 
* Trigger mux state change on peer side, local state will be able to sync up eventually.

### CODE REVIEW

**Comment by zjswhhh** [comment]
> Does `active-active` dualtor have the same issue? And can you add a UT to cover the scenario?

`active-active` won't have this issue, `active-active` has periodical gRPC query at least.

**Review by yxieca — DISMISSED** [review]
Stop sending heatbeats when losing default route is by design.

If you want to change this behavior, then you need to tie the behavior with ignoring default route missing configuration entry.

**Comment by zjswhhh** [comment]
> Stop sending heatbeats when losing default route is by design.
> 
> If you want to change this behavior, then you need to tie the behavior with ignoring default route missing configuration entry.

Hi @yxieca - here we are talking about **mux probe**, not link probe (the heartbeat). The PR is fixing a state machine edge case. By design, it's expected to see **mux probe** when state is unhealthy.

**Review by lolyu — APPROVED** [review]

**Comment by zjswhhh** [comment]
@yxieca - please help review again?

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Please add ADO number in PR description.

**Comment by zjswhhh** [comment]
> Please add ADO number in PR description.

Done.

**Pull request merged**
