### PR TITLE
[CodeQL] fix unmet build dependency

### PR DESCRIPTION
**Pull request by zjswhhh**
### Description of PR

Summary:
Fixes # (issue)
Fix unmet build dependencies. 

sign-off: Jing Zhang zhangjing@microsoft.com 
### Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Doc/Design
- [ ] Unit test

##### Work item tracking
- Microsoft ADO **(number only)**:

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Comment by zjswhhh** [comment]
Issue should be resolved by https://github.com/sonic-net/sonic-linkmgrd/pull/231. 

202205 branch does not need this PR any more.

**Comment by yxieca** [comment]
@zjswhhh please add ADO number to this PR and work on a 202311 PR.

**Comment by zjswhhh** [comment]
> @zjswhhh please add ADO number to this PR and work on a 202311 PR.

Hi @yxieca - this commit is already in 202311 (PR was merged before the cut date).

**Comment by yxieca** [comment]
> > @zjswhhh please add ADO number to this PR and work on a 202311 PR.
> 
> Hi @yxieca - this commit is already in 202311 (PR was merged before the cut date).

@zjswhhh please add ADO number as it went back to earlier branches. thanks.

**Pull request merged**
